services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5210:8080"   # наружный порт
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=LoanDB;Username=postgres;Password=admin
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: LoanDB
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
